# TeachFlow Module Configuration
module_name: TeachFlow
module_code: teachflow
author: Frank
description: Comprehensive teaching workflow system for managing classroom instruction, behavior management, professional responsibilities, and data analysis

# Module paths
module_root: "{project-root}/bmad/teachflow"
installer_path: "{project-root}/bmad/teachflow/_module-installer"

# Component counts
agents:
  count: 11
  core:
    - instructional-designer
    - behavior-specialist
    - professional-writer
    - data-analyst
    - alpha  # Student Support Agent
  supporting:
    - resource-curator
    - accommodation-specialist
    - artifact-generator  # Renamed from report-generator
    - goal-tracker
    - atlas  # Critical Infrastructure - 3D Learning Intelligence Hub
    - qa-validation  # Quality gatekeeper for all outputs

workflows:
  count: 9
  list:
    - lesson-plan-builder
    - behavior-incident-report
    - progress-report-generator
    - assessment-creation
    - differentiation-strategies
    - student-goal-setting
    - classroom-management-plans
    - parent-communication-templates
    - student-support-session  # Alpha-specific workflow

tasks:
  count: 0
  list: []

# Module-specific settings
output_folder: "{project-root}/docs/teachflow"
data_folder: "{module_root}/data"
templates_folder: "{module_root}/templates"

# Agent delegation rules
delegation_enabled: true
delegation_rules:
  instructional-designer:
    can_delegate_to:
      - atlas  # CRITICAL FIRST DELEGATION - provides 3D components
      - resource-curator
      - accommodation-specialist
      - artifact-generator
      - goal-tracker
      - qa-validation  # Validate lesson quality before delivery
  behavior-specialist:
    can_delegate_to:
      - artifact-generator
      - qa-validation
  data-analyst:
    can_delegate_to:
      - artifact-generator
      - goal-tracker
      - qa-validation
  professional-writer:
    can_delegate_to:
      - qa-validation
  alpha:  # Student Support Agent
    can_delegate_to:
      - atlas  # CRITICAL - 3D scope retrieval
      - resource-curator
      - artifact-generator
      - goal-tracker
      - qa-validation  # CRITICAL - validate academic integrity & age-appropriateness
